/* vim: set ts=4 sw=4 et: */

package org.gitorious.scrapfilbleu.android;

import android.util.Log;

public class BusStops {
    public BusStops() {

    }

    public String[] getStops() {
        return new String[] {
            "2 Lions",
            "Abbaye Gatines",
            "Acacias",
            "Adapei",
            "Aérogare",
            "Aitre des Gauthiers",
            "Ajoncs",
            "Aliénor d'Aquitaine",
            "Allende",
            "Alouette",
            "Alsace",
            "Ampère",
            "Anatole France",
            "Anguille",
            "Anne de Bretagne",
            "Anne de France",
            "Apollinaire",
            "Arago",
            "Arche du Lude",
            "Archives",
            "Arsonval",
            "Assas",
            "Ateliers",
            "Atlantes",
            "Aubepines",
            "Audenet",
            "Augereau",
            "Auvergne",
            "Aviron",
            "Azay Le Rideau",
            "Bad Camberg",
            "Baillardière",
            "Ballan Gare",
            "Barberonne",
            "Barbinière",
            "Bas Champeigne",
            "Base 705",
            "Basses Rivières",
            "Baugé",
            "Bd de Chinon",
            "Beaujardin",
            "Beaulieu",
            "Beauregard",
            "Beauverger",
            "Bechellerie",
            "Bedel",
            "Beethoven",
            "Beffroi",
            "Béguine",
            "Béjauderie",
            "Belgique",
            "Belle Isle",
            "Béranger",
            "Berchottière",
            "Bergeonnerie",
            "Bergson",
            "Berthelot",
            "Bialy",
            "Blanqui",
            "Blot",
            "Bocage",
            "Boileau",
            "Bois Aubry",
            "Bois Cormier",
            "Bois de Chambray",
            "Boisdenier",
            "Bois de Plante",
            "Bois des Hâtes",
            "Bois Gibert",
            "Bonamy",
            "Bordiers",
            "Botanique",
            "Bouleaux",
            "Boutteville",
            "Boyer",
            "Boylesve",
            "Branchoire",
            "Brassens",
            "Bretonneau",
            "Bretonnières",
            "Briand",
            "Bruère",
            "Bugeaud",
            "Buisson",
            "Cachin",
            "Calder",
            "Calmette",
            "Camélias",
            "Camus",
            "Camusière",
            "Canal",
            "Canauderie",
            "Cap Soleil",
            "Capucins",
            "Carlotti",
            "Carnot",
            "Casse Droit",
            "Cassin",
            "Castellerie",
            "Cathédrale",
            "Cathelas",
            "CAT Les Vallées",
            "Caulaincourt",
            "Cèdres",
            "CFA Aforproba",
            "CFA Le Bon",
            "Chabottiere",
            "Chagall",
            "Chambray 2",
            "Chambray Centre",
            "Champ Chardon",
            "Champ de Courses",
            "Champ Girault",
            "Champ Joli",
            "Chanceaux Centre",
            "Chantelouze",
            "Chantemerle",
            "Chantepie",
            "Chappe",
            "Charbonniere",
            "Charcot",
            "Charentais",
            "Charleroi",
            "Charles Peguy",
            "Château de Luynes",
            "Château de Tours",
            "Chateau De Villandry",
            "Château Fraisier",
            "Château Gaillard",
            "Châteauneuf",
            "Chatigny",
            "Chaudron",
            "Chaumette",
            "Chemin Vert",
            "Chêne Vert",
            "Chenonceaux",
            "Chevalerie",
            "Chevalette",
            "Chopin",
            "Christ Roi",
            "Churchill",
            "Cimetière des Ricotières",
            "Clarté",
            "Clinique Velpeau",
            "Clocheville",
            "Clos Besnard",
            "Clos de Vernou",
            "Clos Lucé",
            "Clos Mignot",
            "Clos Neuf",
            "Clos Robert",
            "Clos Vaumont",
            "Colette",
            "Collège de Vouvray",
            "Collège Ronsard",
            "Compagnonnage",
            "Condorcet",
            "Constantine",
            "Coppée",
            "Coquinière",
            "Corneille Becquerel",
            "Cornouillers",
            "Cosson",
            "Cottier",
            "Coubertin",
            "Couleuvrou",
            "Coulomb",
            "Courbet",
            "Cousinerie",
            "Cousseau",
            "Croix de Pierre",
            "Croix Pasquier",
            "Croix Perray",
            "Crouzillère",
            "Crucifix",
            "Cugnot",
            "D'Alembert",
            "Dames Blanches",
            "Danemark",
            "Dassault",
            "Debré",
            "De Gaulle",
            "De La Motte",
            "Delaroche",
            "De La Rochefoucauld",
            "Déportés",
            "Deslandes",
            "Desmoulins",
            "Deux Croix",
            "Devildé",
            "Devinière",
            "Dewoitine",
            "D'Indy",
            "Docteur Chaumier",
            "Docteur Fournier",
            "Dorgelès",
            "Douets Lycée Choiseul",
            "Douzillère",
            "Droits de l'Homme",
            "Duclos - Atlantes",
            "Dujardin",
            "Dumont-d'Urville",
            "Duperre",
            "Duplessis",
            "Dupuy",
            "Duquerie",
            "Duquesne",
            "Echeneau",
            "Ecole de Commerce",
            "Ecole d'Infirmières",
            "Ecorcheveau",
            "Eglise de St Avertin",
            "Emile Zola",
            "Erables",
            "Espace Malraux",
            "Estienne d'Orves",
            "Eugénie Grandet",
            "Europarc",
            "Europe",
            "Eve Lavallière",
            "Faculté de Grandmont",
            "Faculté des Tanneurs",
            "Faidherbe",
            "Farges",
            "Fauvettes",
            "Febvotte",
            "Félix",
            "Ferme de la Milletière",
            "Ferranderie",
            "Florian",
            "Foch",
            "Fondettes Centre",
            "Fondettes Gare",
            "Fontaine Blanche",
            "Fontaines",
            "Fontenelles",
            "Forest",
            "Fosse Poitevinne",
            "Fosses Blancs",
            "Fosses Boissées",
            "Fourbisserie",
            "Fourneau",
            "François Sicard",
            "Frasne",
            "Fresnel",
            "Freyssinet",
            "Frumeaud",
            "Fusaparc",
            "Gabrielle d'Estrée",
            "Gagnerie",
            "Galbrunes",
            "Gamard",
            "Gambetta",
            "Gannay",
            "Gare de Tours",
            "Gare Vinci",
            "Gauguin",
            "Général Estienne",
            "Général Mocquery",
            "Général Renault",
            "Giraudeau",
            "Gitonnière",
            "Gloriette",
            "Golf",
            "Grand Carroi",
            "Grand Cour",
            "Grand Mail",
            "Grand Marché",
            "Grand Moulin",
            "Grand Ormeau",
            "Grands Cèdres",
            "Grands Champs",
            "Grands Mortiers",
            "Grand Sud",
            "Grand Théâtre",
            "Grand Village",
            "Grange de Meslay",
            "Granges Galand",
            "Grenouillère",
            "Gros Chêne",
            "Guérin",
            "Guesde",
            "Guesne",
            "Guignardière",
            "Guignière",
            "Guillon",
            "Gutemberg",
            "Guynemer",
            "Halles",
            "Halte Douzillère",
            "Haut-bourg",
            "Haute Limougère",
            "Hautes Roches",
            "Héraults",
            "Hérissières",
            "Heurteloup",
            "Holnon",
            "Homme Noir",
            "Hopital De Luynes",
            "Hôpital Trousseau",
            "Horizon Vert",
            "Hospitalité",
            "Huygens",
            "Ile Aucard",
            "IME",
            "IUT",
            "Jacques Decour",
            "Jacques Monod",
            "Jaunay",
            "Jean Bonnin",
            "Jean de la Fontaine",
            "Jean Jaurès",
            "Jean Moulin",
            "Jeanne D'arc",
            "Jeanne De France",
            "Jéricho",
            "Joffre",
            "Joliot Curie",
            "Jolivet",
            "Jonquilles",
            "Joué Blotterie",
            "Joué Centre",
            "Joué Gare",
            "Joué Lycée Jean Monnet",
            "Joule",
            "J.P. Rameau",
            "Jules Romains",
            "Jumeaux",
            "Katrineholm",
            "Kleber",
            "La Boire Futembre",
            "La Bonde",
            "La Bonnetiere",
            "La Borde",
            "Lac",
            "La Chappe",
            "Lachenal",
            "La Coudrière",
            "La Croix Buissée",
            "La Cure",
            "La Forge",
            "La Fortillère",
            "La Fuye",
            "La Grange",
            "L'aireau Des Bergeons",
            "La Madeleine",
            "Lamartine",
            "Lande",
            "Langennerie",
            "Langevin",
            "La Pasqueraie",
            "La Pécaudinière",
            "La Perouse",
            "La Plaine",
            "La Planche",
            "La Pleiade",
            "La Prévauderie",
            "La Rabinière",
            "L'Arche d'Oé",
            "La Riche Centre",
            "La Riche Soleil",
            "La Taillerie",
            "La Tesserie",
            "La Vallée",
            "La Ville aux Dames Centre",
            "Lebrun",
            "Leccia",
            "Le Chausse",
            "Le Clos",
            "Le Coq",
            "Lecouvreur",
            "Le Marais",
            "Lenine",
            "L'Epend",
            "Le Pin",
            "Le Pluvier",
            "Les Atlantes",
            "Les Aubuis",
            "Le Sauge",
            "Les Bas Chemins",
            "Les Batonneries",
            "Les Bévenières",
            "Les Bidaudières",
            "L'escale",
            "Les Charmes",
            "Les Claies",
            "Les Clouets",
            "Les Ecoles",
            "Les Emmonieres",
            "Les Fougerolles",
            "Les Gatinières",
            "Les Granges",
            "Les Guessières",
            "Les Locquets",
            "Les Montils",
            "Les Muses",
            "Les Nouis",
            "Les Patis",
            "Les Pavillons",
            "L'Espérance",
            "Les Pitoisières",
            "Les Prés de Ballan",
            "Les Rochettes",
            "Les Roncières",
            "Les Sablonnières",
            "L'essart",
            "L'Hopitau",
            "Liberté",
            "Lilas",
            "Loing",
            "Loiseau d'Entraigues",
            "L'Ouche du Mont",
            "Louise Michel",
            "LP Agricole",
            "LP Bayet",
            "LP Clouet",
            "LP Eiffel",
            "LP Nadaud",
            "Luxembourg",
            "Luynes Centre",
            "Lycée Choiseul",
            "Lycée Grandmont",
            "Lycée Paul Louis Courier",
            "Lycée Vaucanson",
            "Maginot",
            "Mailloux",
            "Maine",
            "Mairie De Berthenay",
            "Mairie de Chambray",
            "Maison d'Ardoise",
            "Maison de Beaune",
            "Maisons Blanches",
            "Maisons Rouges",
            "Malines",
            "Mallarme",
            "Manet",
            "Marbellière",
            "Marceau",
            "Marchanderie",
            "Maréchal Juin",
            "Mareuil",
            "Marmoutier",
            "Marteau",
            "Martigny",
            "Martin",
            "Martyrs",
            "Maryse Bastié",
            "Maucannière",
            "Maupas",
            "Maurière",
            "Melies",
            "Mérieux",
            "Mermoz",
            "Mésangerie",
            "Mesliers",
            "Michelin",
            "Mi-Côte",
            "Mignardières",
            "Milletière",
            "Miquel",
            "Mirabeau",
            "Molière",
            "Moncontour",
            "Monsoudun",
            "Montaigne",
            "Monteil",
            "Montjoie",
            "Montjoyeux",
            "Montreuil Bellay",
            "Morier",
            "Mouchotte",
            "Moulin Ragot",
            "Moulin Tann",
            "Mozart",
            "Muguet",
            "Murier",
            "Nationale",
            "Naurod",
            "Nécropole D'esvres",
            "Ninon de l'Enclos",
            "Notre-Dame d'Oé Centre",
            "Nouveau Bois",
            "Observaloire",
            "Ockeghem",
            "Office De Tourisme Villandry",
            "Oiselet",
            "Onze Arpents",
            "Orangerie",
            "Ormeau",
            "Ormes",
            "Pablo Neruda",
            "Palais des Sports",
            "Papoterie",
            "Parcay-Meslay Centre",
            "Parc des Expositions",
            "Parc des Phalènes",
            "Parc Grandmont",
            "Parc Mirabeau",
            "Parc Nord",
            "Passerelle",
            "Passe-temps",
            "Pasteur",
            "Patalisse",
            "Paul Bert",
            "Paul Fort",
            "Pavillon Chinois",
            "Perce Neige",
            "Peri",
            "Perrières",
            "Perriers",
            "Perrin",
            "Petit Bois",
            "Petite Arche",
            "Petites Boucheries",
            "Petit Pré",
            "Petit Versailles",
            "Peupleraie",
            "Peupliers",
            "Philippe Le Bon",
            "Picardie",
            "Pichotière",
            "Pierre Couverte",
            "Pierres Plates",
            "Pinterie",
            "Place Choiseul",
            "Place de la Liberté",
            "Place Tulasne",
            "Place Velpeau",
            "Plantin",
            "Poirrier",
            "Pôle Santé Alliance",
            "Pôle Santé Vinci",
            "Polytech",
            "Pompidou",
            "Pompiers",
            "Pont Cher",
            "Pont de la Motte",
            "Pont du Milieu",
            "Pont Napoleon",
            "Poré",
            "Port de Vallières",
            "Portillon",
            "Portoville",
            "Pot de Fer",
            "Prebendes",
            "Preney",
            "Priestley",
            "Primeveres",
            "Prony",
            "P+R Sagerie",
            "Puits Tessier",
            "Quatre Bornes",
            "Quatre Chemins",
            "Queue de Merluche",
            "Rabelais",
            "Raphaël",
            "Raspail",
            "Rembrandt",
            "Rempart",
            "Renan",
            "Renoir",
            "Republique",
            "Richardières",
            "Richemont",
            "Rimoneaux",
            "Rochebise",
            "Rochecorbon Centre",
            "Rochepinard",
            "Romarins",
            "Rotonde",
            "Rotterdam",
            "Rougemont",
            "Rouget de l'Isle",
            "Rousseau",
            "Route de St-Genouph",
            "Roux",
            "Ruaux",
            "Rue Neuve",
            "Rue Noire",
            "Saboterie",
            "Sagerie",
            "Sainterie",
            "Salengro",
            "Sanitas",
            "Sapaille",
            "Saulnier",
            "Savonnieres Grottes Petrifiantes",
            "Savonnieres Poste",
            "Schweitzer",
            "Scotto",
            "Semard",
            "Séverine",
            "Sévigné",
            "Sibotière",
            "Simone Signoret",
            "Sorbiers",
            "Stade",
            "Stade Varenne",
            "Stalingrad",
            "St Augustin",
            "St Avertin Centre",
            "St Avertin Mairie",
            "St Barthélemy",
            "St Cyr Croix Chidaine",
            "St Cyr Eglise",
            "St Cyr Equatop",
            "St Cyr Mairie",
            "Ste Agathe",
            "Ste Anne",
            "St Eloi",
            "Stendhal",
            "Ste Radegonde",
            "Ste Radegonde Centre",
            "Ste Radegonde-Ermitage",
            "St Etienne de Chigny Centre",
            "Ste Ursule",
            "St Exupery",
            "St François",
            "St Gatien",
            "St Georges",
            "St Joseph",
            "St Léger",
            "St Libert",
            "St Malo",
            "St Martin",
            "St Paul",
            "St Pierre Centre",
            "St Pierre Gare",
            "St Pierre Justices",
            "Strasbourg",
            "St Roch",
            "St Sauveur",
            "St Symphorien",
            "St Venant",
            "St Vincent",
            "Suède",
            "Tamaris",
            "Tanneurs",
            "Tartifume",
            "Tavant",
            "Terre Fortes",
            "Terres Rouges",
            "Thalès",
            "Thibaudière",
            "Thorez",
            "Tilleuls",
            "Tonnellé",
            "Torricelli",
            "Tour d'Auvergne",
            "Tourettes",
            "Touvoie",
            "Tranchée",
            "Traversiere",
            "Tremblay",
            "Trianon",
            "Trobriand",
            "Troènes",
            "Trois Rivières",
            "Trois Tonneaux",
            "Tulipes",
            "Ursulines",
            "Val Fleuri",
            "Vallée Chartier",
            "Vallée Violette",
            "Vallières",
            "Vanneaux",
            "Vaudasnière",
            "Vaugareau",
            "Vauvert",
            "Venien",
            "Verdun",
            "Vernou Centre",
            "Viala",
            "Victor Hugo",
            "Vieux Bourg",
            "Villandry Chateau Galle",
            "Voisin",
            "Voltaire",
            "Vouvray Centre",
            "Vrillonnerie",
            "Wedells",
            "Willy Brandt",
            "ZA d'Oé",
            "ZA Papillon",
            "ZI Les Aubuis"
        };
    }
}
